config/routes.rb
Rails.application.routes.draw do
  require 'admin_constraint'
  mount Ckeditor::Engine => '/ckeditor', constraints: AdminConstraint.new
  root 'home#index'
  resources :profiles, except: [:index]

  match '/who-we-are'              =>        'home#who_we_are',              via: [:get],            :as => 'who_we_are'
  # match '/gallery'              =>        'home#gallery',              via: [:get],            :as => 'gallery'
 
  match '/join-our-team'              =>        'home#join_our_team',              via: [:get],            :as => 'join_our_team'
  # match '/clients'              =>        'home#clients',              via: [:get],            :as => 'clients'
  # match '/affiliations'              =>        'home#affiliations',              via: [:get],            :as => 'affiliations'
  match '/privacy-policy'              =>        'home#privacy_policy',              via: [:get],            :as => 'privacy_policy'


  match '/what-we-do'                 =>        'what_we_do#what_we_do',              via: [:get],            :as => 'what_we_do'
  match '/social-events'              =>        'what_we_do#social_events',              via: [:get],            :as => 'social_events'
  match '/weddings'              =>        'what_we_do#weddings',              via: [:get],            :as => 'weddings'
  match '/corporate-events-catering'              =>        'what_we_do#corporate_events',              via: [:get],            :as => 'corporate_events'
  match '/sporting-events-catering'              =>        'what_we_do#sporting_events',              via: [:get],            :as => 'sporting_events'
  match '/government-events-catering'              =>        'what_we_do#government_events',              via: [:get],            :as => 'government_events'

  match '/gallery'              =>        'gallery_images#index',              via: [:get],            :as => 'gallery'
  match '/gallery/new'              =>        'gallery_images#new',              via: [:get],            :as => 'new_gallery'
  match '/gallery'              =>        'gallery_images#create',              via: [:post]
  match '/gallery/:id'              =>        'gallery_images#destroy',              via: [:delete], :as => 'delete_gallery'

  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end  
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end

  #########################################
  #==locations url for location model
  #########################################
    # get '/locations', to: 'locations#index', as: :locations
    post 'locations', to: 'locations#create'
    get '/locations/new', to: 'locations#new', as: :new_location
    get 'locations/:title_for_slug/edit', to: 'locations#edit', as: 'edit_location'
    get 'locations/:title_for_slug', to: 'locations#show', as: 'location'
    patch 'locations/:title_for_slug', to: 'locations#update'
    put 'locations/:title_for_slug', to: 'locations#update'
    delete 'locations/:title_for_slug', to: 'locations#destroy'

  #########################################
  #==news url for blog model
  #########################################
    get '/news', to: 'blogs#index', as: :blogs
    post 'news', to: 'blogs#create'
    get '/news/new', to: 'blogs#new', as: :new_blog
    get 'news/:title_for_slug/edit', to: 'blogs#edit', as: 'edit_blog'
    get 'news/:title_for_slug', to: 'blogs#show', as: 'blog'
    patch 'news/:title_for_slug', to: 'blogs#update'
    put 'news/:title_for_slug', to: 'blogs#update'
    delete 'news/:title_for_slug', to: 'blogs#destroy'
    
  match "/contacts"              =>        "contacts#create",              via: [:post]
  match "/applicants"            =>        "applicants#create",            via: [:post]

  get '/sitemap.xml', to: redirect("https://s3-us-west-2.amazonaws.com/gcg-events/sitemaps/sitemap.xml.gz", status: 301)

  match "*path", to: "home#catch_all", via: :all

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :location
  has_one :image, as: :imageable, :class_name => "Profile::Asset", dependent: :destroy
  accepts_nested_attributes_for :image, update_only: true #otherwise it will delete and then reinsert everytime you reach the edit page, instead of updating it
  # accepts_nested_attributes_for :image, allow_destroy: true # use above for has one relationship
end

app/models/profile/asset.rb
class Profile::Asset < Image
  
  ##============================================================##
  ## Paperclip Interpolates
  ##============================================================##
  Paperclip.interpolates :imageable_type do |attachment, style|
    attachment.instance.imageable_type.downcase
  end

  Paperclip.interpolates :imageable_id do |attachment, style|
    attachment.instance.imageable_id
  end

  has_attached_file :pic,
    :path => "#{Rails.env}/:imageable_type/:imageable_id/:style/:filename",
    :styles => { 
      :square => ["300x300#", :jpg]
    },
    default_url: "//s3.amazonaws.com/gcg-ground/general/no-profile-image.png",
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }



  validates_attachment :pic, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true

end


#needed default_url here because in the new action the build method semi-creates an image, and needs a default image otherwise it would say missing

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :create, :destroy]
  
  respond_to :html, :json

  def index
    @profiles = Profile.all
  end

  def update
    # Commented section is for best_in_place gem
    # @profile.update(profile_params)
    # respond_with @profile

    # We need to use build here, because rails by default will destroy and create an image (has one association) 
    # since its a has one relationship rails's build method does not know how to update(i think), it just deletes and creates a new record
    if profile_params[:image_attributes][:pic].present?
      @profile.build_image
    end

    if @profile.update(profile_params)
      # redirect_to "/location-#{profile_params[:location].downcase}", notice: 'Profile was successfully updated.'
      redirect_to root_path
    else
      render :edit
    end

  end

  def new
    @profile = Profile.new
    @profile.build_image
  end

  def edit
  end



  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      # redirect_to "/location-#{profile_params[:location].downcase}", notice: 'Profile was successfully created.'
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @profile.destroy
    redirect_to :back, notice: 'Profile was successfully destroyed.'
  end

  private

    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:full_name, :title, :telephone, :mobile, :email, :location, :position, :location_id, image_attributes: [:id, :pic, :name])
    end

end

app/views/profiles/_form.html.erb
<%= form_for(@profile, :url => (@profile.new_record? ? profiles_url : profile_path(@profile)), :html => { :multipart => true }) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :full_name %>
    <%= f.text_field :full_name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :telephone %>
    <%= f.text_field :telephone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :mobile %>
    <%= f.text_field :mobile, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <!-- <div class="form-group"> -->
    <%#= f.label :location %>
    <%#= f.select(:location, [["Florida", "Florida"], ["Kingston", "Kingston"], ["Montego-Bay", "Montego-Bay"], ["St-Thomas", "St-Thomas"]], {include_blank: true}, {required: true, class: "form-control" })  %>
  <!-- </div> -->

  <div class="form-group">
    <%= f.hidden_field :location_id, value: params[:location_id] %>
  </div>

  <div class="form-group">
    <%= f.label :position %>
    <%= f.number_field :position, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.fields_for :image do |t| %>
      <%= t.label :pic, "Main Image (for best results upload square photo)" %> <br>

      <% if @profile.image.present? %>
        <%= image_tag @profile.image.pic.url(:square), id: 'square_image', class: 'mb15' %><br/>
      <% else %>
        <img id="square_image" class="mb5" src="#" alt="">
      <% end %>
      <% if current_page?('/profiles/new') %>
        <%= t.file_field :pic, class: "form-control", style: "padding: 4px;", required: true %>  
      <% else %>
        <%= t.file_field :pic, class: "form-control", style: "padding: 4px;" %>
      <% end %>

    <% end %>
  </div>

  <div class="form-group">
    <%= f.submit class: "form-control btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4 col-lg-offset-4">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4 col-lg-offset-4">
      <%= render 'form' %>
    </div>
  </div>
</div>