config/routes.rb
Rails.application.routes.draw do
  require 'admin_constraint'
  mount Ckeditor::Engine => '/ckeditor', constraints: AdminConstraint.new
  root 'home#index'
  resources :profiles, except: [:index]

  match '/who-we-are'              =>        'home#who_we_are',              via: [:get],            :as => 'who_we_are'
  # match '/gallery'              =>        'home#gallery',              via: [:get],            :as => 'gallery'
 
  match '/join-our-team'              =>        'home#join_our_team',              via: [:get],            :as => 'join_our_team'
  # match '/clients'              =>        'home#clients',              via: [:get],            :as => 'clients'
  # match '/affiliations'              =>        'home#affiliations',              via: [:get],            :as => 'affiliations'
  match '/privacy-policy'              =>        'home#privacy_policy',              via: [:get],            :as => 'privacy_policy'


  match '/what-we-do'                 =>        'what_we_do#what_we_do',              via: [:get],            :as => 'what_we_do'
  match '/social-events'              =>        'what_we_do#social_events',              via: [:get],            :as => 'social_events'
  match '/weddings'              =>        'what_we_do#weddings',              via: [:get],            :as => 'weddings'
  match '/corporate-events-catering'              =>        'what_we_do#corporate_events',              via: [:get],            :as => 'corporate_events'
  match '/sporting-events-catering'              =>        'what_we_do#sporting_events',              via: [:get],            :as => 'sporting_events'
  match '/government-events-catering'              =>        'what_we_do#government_events',              via: [:get],            :as => 'government_events'

  match '/gallery'              =>        'gallery_images#index',              via: [:get],            :as => 'gallery'
  match '/gallery/new'              =>        'gallery_images#new',              via: [:get],            :as => 'new_gallery'
  match '/gallery'              =>        'gallery_images#create',              via: [:post]
  match '/gallery/:id'              =>        'gallery_images#destroy',              via: [:delete], :as => 'delete_gallery'

  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end  
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end

  #########################################
  #==locations url for location model
  #########################################
    # get '/locations', to: 'locations#index', as: :locations
    post 'locations', to: 'locations#create'
    get '/locations/new', to: 'locations#new', as: :new_location
    get 'locations/:title_for_slug/edit', to: 'locations#edit', as: 'edit_location'
    get 'locations/:title_for_slug', to: 'locations#show', as: 'location'
    patch 'locations/:title_for_slug', to: 'locations#update'
    put 'locations/:title_for_slug', to: 'locations#update'
    delete 'locations/:title_for_slug', to: 'locations#destroy'

  #########################################
  #==news url for blog model
  #########################################
    get '/news', to: 'blogs#index', as: :blogs
    post 'news', to: 'blogs#create'
    get '/news/new', to: 'blogs#new', as: :new_blog
    get 'news/:title_for_slug/edit', to: 'blogs#edit', as: 'edit_blog'
    get 'news/:title_for_slug', to: 'blogs#show', as: 'blog'
    patch 'news/:title_for_slug', to: 'blogs#update'
    put 'news/:title_for_slug', to: 'blogs#update'
    delete 'news/:title_for_slug', to: 'blogs#destroy'
    
  match "/contacts"              =>        "contacts#create",              via: [:post]
  match "/applicants"            =>        "applicants#create",            via: [:post]

  get '/sitemap.xml', to: redirect("https://s3-us-west-2.amazonaws.com/gcg-events/sitemaps/sitemap.xml.gz", status: 301)

  match "*path", to: "home#catch_all", via: :all

end

app/models/blog.rb
class Blog < ApplicationRecord

  before_save :title_url_it
  before_save :remove_img

  has_many :images, as: :imageable, :class_name => "Blog::Asset", dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  
  #This is for SEO purposes, you want the url to be the title of the blog instead of its ID
  def title_url_it
    self.title_for_slug = title.downcase.squish.parameterize("-")
  end

  def remove_img
    nokogiri_html_document =  Nokogiri::HTML(self.content) #heroku does not like tmp directory
    nokogiri_html_document.search('img').each do |img|
      img.remove
    end
    self.content_index = nokogiri_html_document
    #note that if you call self.save here, you might run into infinite loops (stack level too deep), even for after_save, after_create and after_update callbacks
  end

end

app/models/blog/asset.rb
class Blog::Asset < Image
  
  ##============================================================##
  ## Paperclip Interpolates
  ##============================================================##
  Paperclip.interpolates :imageable_type do |attachment, style|
    attachment.instance.imageable_type.downcase
  end

  Paperclip.interpolates :imageable_id do |attachment, style|
    attachment.instance.imageable_id
  end

  has_attached_file :pic,
    :path => "#{Rails.env}/:imageable_type/:imageable_id/:style/:filename",
    :styles => { 
      :medium => ["300x190>", :jpg], 
      :large => ["825x523>", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

  validates_attachment :pic, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @blogs = Blog.order(pubdate: :desc)
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blog_path(@blog.title_for_slug), notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blog_path(@blog.title_for_slug), notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
  end

  private

    def set_blog
      @blog = Blog.find_by(title_for_slug: params[:title_for_slug])
    end

    def blog_params
      params.require(:blog).permit(:title, :content, :content_index, :title_for_slug, :main_image, :pubdate, :meta_description, :meta_keywords, images_attributes: [:id, :pic, :name, :_destroy])
    end

end

app/views/blogs/_form.html.erb
<%= form_for(blog, :url => (blog.new_record? ? blogs_url : blog_path(blog.title_for_slug)), :html => { :multipart => true }) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.cktext_area :content, class: "form-control ckeditor" %>
  </div>

  <div class="form-group">
    <%= f.label :meta_description %>
    <%= f.text_field :meta_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :meta_keywords %>
    <%= f.text_field :meta_keywords, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.fields_for :images, @blog.images.build do |t| %>
      <%= t.label :pic, "Main Image" %> <br>

      <% if @blog.images.exists? %>
        <%= image_tag @blog.images[0].pic.url(:medium), id: 'current_image', class: 'mb15' %><br/>
      <% else %>
        <img id="current_image" class="mb5" src="#" alt="">
      <% end %>

      <%= t.file_field :pic, style: "padding: 4px;" %>  
      <%#= In order to make multiple file uploads you'd have to do it like you did in oldpalm, add multiple true, and loop through params[:pic] in your controller and create images that way %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :pubdate %><br>
    <%= f.date_field :pubdate, value: Date.today, class:'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.submit class: "form-control btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<% provide(:title, 'GCG Events | Press') %>
<% content_for :head do%>
  <!-- <meta name="description" content="home description"> -->
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">

      <h1>Editing Blog</h1>

      <%= render 'form', blog: @blog %>

      <div class="mt15 mb30">
        <%= link_to '< Back', blogs_path, class: 'btn btn-default' %>
        <%= link_to 'Show Blog', blogs_path(@blog.title_for_slug), class: 'btn btn-default' %> 
      </div>

    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<% provide(:title, 'GCG Events | Press') %>
<% content_for :head do%>
  <meta name="description" content="See what people are saying about GCG Events all around the globe.">
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<section class="hero-press">
    <!-- <div class="hero-text">
      <h2 class="big">GCG in the News</h2>
    </div> -->
</section>

<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="text-center mb90">News<%= link_to "New Press", new_blog_path, class:"btn btn-primary btnNewBlog btn-custom-primary" if current_user.try(:admin?) %></h3>
        <p class="text-center mb30">Whether guests are raving about the mouthwatering food or commending the supreme level of service, events catered by our international catering company are known to get people talking. See what people are saying about GCG Events.</p>
      </div>
    </div>
  </div>
</section>

<!-- press  -->
<section class="bg-light-grey">
  <div class="container">
  <% @blogs.each do |blog| %>
    <div class="row">
      <div class="box-press">
        <div class="col-md-3 col-sm-4">
          <a href="<%= blog_path(blog.title_for_slug) %>"><div class="img-blog"  style="background-image: url(<%= blog.images[-1].pic.url(:large) %>);"></div></a>
        </div>
        <div class="col-md-9 col-sm-8">
          <h4 class="color-secondary"><%= blog.title %></h4>
          <p class="small"><%= blog.pubdate.strftime("%B %d, %Y") %></p>
          <p class="mt15 mb15"><%= HTML_Truncator.truncate(blog.content_index, 75).html_safe %></p>
          <%= link_to 'Read More', blog_path(blog.title_for_slug), class:"btn btn-custom-primary-border transition pl30 pr30 mt15" %>
          <%= link_to 'Edit', edit_blog_path(blog.title_for_slug), class:"btn btn-custom-primary-border transition pl30 pr30 mt15" if current_user.try(:admin?) %>
          <%= link_to 'Destroy', blog_path(blog.title_for_slug), class:"btn btn-custom-primary-border transition pl30 pr30 mt15", method: :delete, data: { confirm: 'Are you sure?' } if current_user.try(:admin?) %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</section>

<!-- gallery  -->
<%= render 'layouts/gallery' %>

<!-- Services  -->
<%= render 'layouts/services2' %>

app/views/blogs/new.html.erb
<% provide(:title, 'GCG Events | Press') %>
<% content_for :head do%>
  <!-- <meta name="description" content="home description"> -->
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<section class="bgGrey">
	<div class="container">
	  <div class="row">
	    <div class="col-lg-6 col-lg-offset-3">
	      <h1>New Blog</h1>

	      <%= render 'form', blog: @blog %>

	      <div class="mt30 mb30">
	         <%= link_to 'Back', blogs_path, class: 'btn btn-default' %>
	      </div>
	     
	    </div>
	  </div>
	</div>
</section>

app/views/blogs/show.html.erb
<% provide(:title, "GCG Events News | #{@blog.title}") %>
<% content_for :head do%>
  <meta name="description" content="<%= @blog.meta_description %>">
  <meta name="keywords" content="<%= @blog.meta_keywords %>">
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<section class="bgGrey">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <h4 class="color-secondary"><%= @blog.title %></h4>
        <p class="small mb30"><%= @blog.pubdate.strftime("%B %d, %Y") if @blog.pubdate.present? %></p>

        <%= image_tag(@blog.images[-1].pic.url(:large), class:'img-responsive imgbig') if @blog.images.present? %>
        <p class="mt30"><%= @blog.content.html_safe %></p>
        <div class="mt30">
          <%= link_to 'Edit', edit_blog_path(@blog.title_for_slug), class: "btn btn-custom-primary-border transition pl30 pr30 mt15" if current_user.try(:admin?) %>
          <%= link_to 'Back', blogs_path, class: "btn btn-custom-primary-border transition pl30 pr30 mt15" %>
        </div>
      </div>
    </div>

  </div>
</section>