config/routes.rb
Rails.application.routes.draw do
  require 'admin_constraint'
  mount Ckeditor::Engine => '/ckeditor', constraints: AdminConstraint.new
  root 'home#index'
  resources :profiles, except: [:index]

  match '/who-we-are'              =>        'home#who_we_are',              via: [:get],            :as => 'who_we_are'
  # match '/gallery'              =>        'home#gallery',              via: [:get],            :as => 'gallery'
 
  match '/join-our-team'              =>        'home#join_our_team',              via: [:get],            :as => 'join_our_team'
  # match '/clients'              =>        'home#clients',              via: [:get],            :as => 'clients'
  # match '/affiliations'              =>        'home#affiliations',              via: [:get],            :as => 'affiliations'
  match '/privacy-policy'              =>        'home#privacy_policy',              via: [:get],            :as => 'privacy_policy'


  match '/what-we-do'                 =>        'what_we_do#what_we_do',              via: [:get],            :as => 'what_we_do'
  match '/social-events'              =>        'what_we_do#social_events',              via: [:get],            :as => 'social_events'
  match '/weddings'              =>        'what_we_do#weddings',              via: [:get],            :as => 'weddings'
  match '/corporate-events-catering'              =>        'what_we_do#corporate_events',              via: [:get],            :as => 'corporate_events'
  match '/sporting-events-catering'              =>        'what_we_do#sporting_events',              via: [:get],            :as => 'sporting_events'
  match '/government-events-catering'              =>        'what_we_do#government_events',              via: [:get],            :as => 'government_events'

  match '/gallery'              =>        'gallery_images#index',              via: [:get],            :as => 'gallery'
  match '/gallery/new'              =>        'gallery_images#new',              via: [:get],            :as => 'new_gallery'
  match '/gallery'              =>        'gallery_images#create',              via: [:post]
  match '/gallery/:id'              =>        'gallery_images#destroy',              via: [:delete], :as => 'delete_gallery'

  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end  
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end

  #########################################
  #==locations url for location model
  #########################################
    # get '/locations', to: 'locations#index', as: :locations
    post 'locations', to: 'locations#create'
    get '/locations/new', to: 'locations#new', as: :new_location
    get 'locations/:title_for_slug/edit', to: 'locations#edit', as: 'edit_location'
    get 'locations/:title_for_slug', to: 'locations#show', as: 'location'
    patch 'locations/:title_for_slug', to: 'locations#update'
    put 'locations/:title_for_slug', to: 'locations#update'
    delete 'locations/:title_for_slug', to: 'locations#destroy'

  #########################################
  #==news url for blog model
  #########################################
    get '/news', to: 'blogs#index', as: :blogs
    post 'news', to: 'blogs#create'
    get '/news/new', to: 'blogs#new', as: :new_blog
    get 'news/:title_for_slug/edit', to: 'blogs#edit', as: 'edit_blog'
    get 'news/:title_for_slug', to: 'blogs#show', as: 'blog'
    patch 'news/:title_for_slug', to: 'blogs#update'
    put 'news/:title_for_slug', to: 'blogs#update'
    delete 'news/:title_for_slug', to: 'blogs#destroy'
    
  match "/contacts"              =>        "contacts#create",              via: [:post]
  match "/applicants"            =>        "applicants#create",            via: [:post]

  get '/sitemap.xml', to: redirect("https://s3-us-west-2.amazonaws.com/gcg-events/sitemaps/sitemap.xml.gz", status: 301)

  match "*path", to: "home#catch_all", via: :all

end

app/models/gallery_image.rb
class GalleryImage < ApplicationRecord

  Paperclip.interpolates :id do |attachment, style|
    attachment.instance.id
  end

  has_attached_file :pic,
    :path => "#{Rails.env}/gallery_image/:id/:style/:filename",
    :styles => { 
      :large => ["900x600>", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

  validates_attachment :pic, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true
end

app/models/gallery_image/asset.rb
class GalleryImage::Asset < Image
  
  ##============================================================##
  ## Paperclip Interpolates
  ##============================================================##
  Paperclip.interpolates :imageable_type do |attachment, style|
    attachment.instance.imageable_type.downcase
  end

  Paperclip.interpolates :imageable_id do |attachment, style|
    attachment.instance.imageable_id
  end

  has_attached_file :pic,
    :path => "#{Rails.env}/:imageable_type/:imageable_id/:style/:filename",
    :styles => { 
      :large => ["900x600>", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

  validates_attachment :pic, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true

end

app/controllers/gallery_images_controller.rb
class GalleryImagesController < ApplicationController
  # before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  def index
    @gallery_images = GalleryImage.order(position: :asc)
  end

  def new
    @gallery_image = GalleryImage.new
  end

  def create
    @gallery_image = GalleryImage.new(gallery_image_params)
    if @gallery_image.save
      redirect_to gallery_path, notice: 'Gallery image was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @gallery_image = GalleryImage.find(params[:id])
    @gallery_image.destroy
    redirect_to gallery_url, notice: 'Gallery image was successfully destroyed.'
  end

  private

    def gallery_image_params
      params.require(:gallery_image).permit(:position, :pic)
    end

end

app/views/gallery_images/index.html.erb
<% provide(:title, 'GCG Events | Event Catering Gallery') %>
<% content_for :head do%>
  <meta name="description" content="GCG Events has plenty of experience catering events from large to small, peruse our gallery for an intimate look into our capabilities.">
  <!-- <meta name="keywords" content="about keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<!-- Hero  -->
<section class="hero-gallery">
    <!-- <div class="hero-text">
      <h2 class="big">GCG in photos</h2>
    </div> -->
</section>


<!-- gallery  -->
<section class="gallery">
  <div class="container">
    <div class="row">
          
          <% if current_user.try(:admin?) %>
            <div class="col-sm-12 text-center mb35">
              <a href="/gallery/new"><h1>Add new Gallery Image</h1></a>
            </div>
          <% end %>

          <% @gallery_images.to_enum.each_slice(6).to_a.each do | group_img | %>
          <% group_img.each_with_index do |img, i| %>
            <% if i == 0 %>
            <div class="col-md-3 col-sm-6 item-img">
              <div class="content-img" title="Catered Caribbean and Latin America Events by GCG Events" style='background-image: url("<%= img.pic.url(:large) %>");'></div>
              <%= link_to 'Delete',  delete_gallery_path(img), data: { confirm: 'Are you sure?' }, method: :delete if current_user.try(:admin?) %>
              <%= "<span>&nbsp;&nbsp;position: #{img.position}</span>".html_safe if current_user.try(:admin?) %>
            </div>
            <% elsif i == 1 %>
            <div class="col-md-6 col-sm-6 item-img">
              <div class="content-img" title="Catered Caribbean and Latin America Events by GCG Events" style='background-image: url("<%= img.pic.url(:large) %>");'></div>
              <%= link_to 'Delete',  delete_gallery_path(img), data: { confirm: 'Are you sure?' }, method: :delete if current_user.try(:admin?) %>
               <%= "<span>&nbsp;&nbsp;position: #{img.position}</span>".html_safe if current_user.try(:admin?) %>
            </div>
            <% elsif i == 2 %>
            <div class="col-md-3 col-sm-6 item-img">
              <div class="content-img" title="Catered Caribbean and Latin America Events by GCG Events" style='background-image: url("<%= img.pic.url(:large) %>");'></div>
              <%= link_to 'Delete',  delete_gallery_path(img), data: { confirm: 'Are you sure?' }, method: :delete if current_user.try(:admin?) %>
               <%= "<span>&nbsp;&nbsp;position: #{img.position}</span>".html_safe if current_user.try(:admin?) %>
            </div>
            <% elsif i == 3 %>
            <div class="col-md-5 col-sm-6 item-img">
              <div class="content-img" title="Catered Caribbean and Latin America Events by GCG Events" style='background-image: url("<%= img.pic.url(:large) %>");'></div>
              <%= link_to 'Delete',  delete_gallery_path(img), data: { confirm: 'Are you sure?' }, method: :delete if current_user.try(:admin?) %>
               <%= "<span>&nbsp;&nbsp;position: #{img.position}</span>".html_safe if current_user.try(:admin?) %>
            </div>
            <% elsif i == 4 %>
            <div class="col-md-3 col-sm-6 item-img">
              <div class="content-img" title="Catered Caribbean and Latin America Events by GCG Events" style='background-image: url("<%= img.pic.url(:large) %>");'></div>
              <%= link_to 'Delete',  delete_gallery_path(img), data: { confirm: 'Are you sure?' }, method: :delete if current_user.try(:admin?) %>
               <%= "<span>&nbsp;&nbsp;position: #{img.position}</span>".html_safe if current_user.try(:admin?) %>
            </div>
            <% elsif i == 5 %>
            <div class="col-md-4 col-sm-6 item-img">
              <div class="content-img" title="Catered Caribbean and Latin America Events by GCG Events" style='background-image: url("<%= img.pic.url(:large) %>");'></div>
              <%= link_to 'Delete',  delete_gallery_path(img), data: { confirm: 'Are you sure?' }, method: :delete if current_user.try(:admin?) %>
               <%= "<span>&nbsp;&nbsp;position: #{img.position}</span>".html_safe if current_user.try(:admin?) %>
            </div>
            <% end %>
          <% end %>
          <% end if @gallery_images.present?%>

      </div>
    </div>
  </div>
</section>

app/views/gallery_images/new.html.erb
<section class="bgGrey">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3">
        <h1>New Gallery Image</h1>
        
        <%= form_for(@gallery_image, url:  gallery_path, :html => { :multipart => true }) do |f| %>
          <% if @gallery_image.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@gallery_image.errors.count, "error") %> prohibited this gallery image from being saved:</h2>

              <ul>
              <% @gallery_image.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.label :pic, "Upload Gallery Image" %> <br>
            <%= f.file_field :pic, style: "padding: 4px;", required: true %>  
            <%#= In order to make multiple file uploads you'd have to do it like you did in oldpalm, add multiple true, and loop through params[:pic] in your controller and create images that way %>
          </div>

          <div class="form-group">
            <%= f.label :position %>
            <%= f.number_field :position, class: "form-control text_field", step: 0.01 %>
          </div>

          <div class="form-group">
            <%= f.submit class: "form-control btn btn-primary" %>
          </div>
        <% end %>

        <div class="mt30 mb30">
           <%= link_to 'Back', gallery_path, class: 'btn btn-default' %>
        </div>
       
      </div>
    </div>
  </div>
</section>