config/routes.rb
Rails.application.routes.draw do
  require 'admin_constraint'
  mount Ckeditor::Engine => '/ckeditor', constraints: AdminConstraint.new
  root 'home#index'
  resources :profiles, except: [:index]

  match '/who-we-are'              =>        'home#who_we_are',              via: [:get],            :as => 'who_we_are'
  # match '/gallery'              =>        'home#gallery',              via: [:get],            :as => 'gallery'
 
  match '/join-our-team'              =>        'home#join_our_team',              via: [:get],            :as => 'join_our_team'
  # match '/clients'              =>        'home#clients',              via: [:get],            :as => 'clients'
  # match '/affiliations'              =>        'home#affiliations',              via: [:get],            :as => 'affiliations'
  match '/privacy-policy'              =>        'home#privacy_policy',              via: [:get],            :as => 'privacy_policy'


  match '/what-we-do'                 =>        'what_we_do#what_we_do',              via: [:get],            :as => 'what_we_do'
  match '/social-events'              =>        'what_we_do#social_events',              via: [:get],            :as => 'social_events'
  match '/weddings'              =>        'what_we_do#weddings',              via: [:get],            :as => 'weddings'
  match '/corporate-events-catering'              =>        'what_we_do#corporate_events',              via: [:get],            :as => 'corporate_events'
  match '/sporting-events-catering'              =>        'what_we_do#sporting_events',              via: [:get],            :as => 'sporting_events'
  match '/government-events-catering'              =>        'what_we_do#government_events',              via: [:get],            :as => 'government_events'

  match '/gallery'              =>        'gallery_images#index',              via: [:get],            :as => 'gallery'
  match '/gallery/new'              =>        'gallery_images#new',              via: [:get],            :as => 'new_gallery'
  match '/gallery'              =>        'gallery_images#create',              via: [:post]
  match '/gallery/:id'              =>        'gallery_images#destroy',              via: [:delete], :as => 'delete_gallery'

  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end  
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end

  #########################################
  #==locations url for location model
  #########################################
    # get '/locations', to: 'locations#index', as: :locations
    post 'locations', to: 'locations#create'
    get '/locations/new', to: 'locations#new', as: :new_location
    get 'locations/:title_for_slug/edit', to: 'locations#edit', as: 'edit_location'
    get 'locations/:title_for_slug', to: 'locations#show', as: 'location'
    patch 'locations/:title_for_slug', to: 'locations#update'
    put 'locations/:title_for_slug', to: 'locations#update'
    delete 'locations/:title_for_slug', to: 'locations#destroy'

  #########################################
  #==news url for blog model
  #########################################
    get '/news', to: 'blogs#index', as: :blogs
    post 'news', to: 'blogs#create'
    get '/news/new', to: 'blogs#new', as: :new_blog
    get 'news/:title_for_slug/edit', to: 'blogs#edit', as: 'edit_blog'
    get 'news/:title_for_slug', to: 'blogs#show', as: 'blog'
    patch 'news/:title_for_slug', to: 'blogs#update'
    put 'news/:title_for_slug', to: 'blogs#update'
    delete 'news/:title_for_slug', to: 'blogs#destroy'
    
  match "/contacts"              =>        "contacts#create",              via: [:post]
  match "/applicants"            =>        "applicants#create",            via: [:post]

  get '/sitemap.xml', to: redirect("https://s3-us-west-2.amazonaws.com/gcg-events/sitemaps/sitemap.xml.gz", status: 301)

  match "*path", to: "home#catch_all", via: :all

end

app/models/location.rb
class Location < ApplicationRecord
  has_many :applicants

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  has_many :profiles
  before_save :title_url_it
  has_one :image, as: :imageable, :class_name => "Location::Asset", dependent: :destroy
  accepts_nested_attributes_for :image, update_only: true #otherwise it will delete and then reinsert everytime you reach the edit page, instead of updating it
  # accepts_nested_attributes_for :image, allow_destroy: true # use above for has one relationship

  def title_url_it
    self.title_for_slug = name.downcase.squish.parameterize("-")
  end



end

app/models/location/asset.rb
class Location::Asset < Image

  validate :check_dimensions

  def check_dimensions
    temp_file = pic.queued_for_write[:original]
    unless temp_file.nil?
      dimensions = Paperclip::Geometry.from_file(temp_file)
      width = dimensions.width
      height = dimensions.height
      
      if width < 1500 && height < 750
        errors[''] << " dimensions are too small. For a good quality background please upload a larger image. Minimum width: 1500px, minimum height: 750px"
      end
    end
  end
  
  ##============================================================##
  ## Paperclip Interpolates
  ##============================================================##
  Paperclip.interpolates :imageable_type do |attachment, style|
    attachment.instance.imageable_type.downcase
  end

  Paperclip.interpolates :imageable_id do |attachment, style|
    attachment.instance.imageable_id
  end

  has_attached_file :pic,
    :path => "#{Rails.env}/:imageable_type/:imageable_id/:style/:filename",
    :styles => { 
      :big => ["1500x750>", :jpg]
    },
    # default_url: "//s3-us-west-2.amazonaws.com/gcg-catering/hero/hero-locations.jpg",
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }



  validates_attachment :pic, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true

end


#needed default_url here because in the new action the build method semi-creates an image, and needs a default image otherwise it would say missing

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :create, :destroy]

  def show
    # @profiles = Profile.all
    @profiles = @location.profiles.order(position: "asc")
  end

  def new
    @location = Location.new
    @location.build_image
  end

  def edit
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to root_path, notice: "Location was created successfully"
    else
      render :new
    end
  end

  def update
    if @location.update(location_params)
      redirect_to root_path, notice: "Location was successfully updated"
    else
      render :edit
    end
  end

  private

  def set_location
    @location = Location.find_by(title_for_slug: params[:title_for_slug])
  end

  def location_params
    params.require(:location).permit(:name, :title_for_slug, :description, :address, :latitude, :longitude, :title_for_maps, :phone, :fax, :general_contact_email, :specific_location, :iframe, image_attributes: [:id, :pic, :name])
  end

end

app/views/locations/_form.html.erb
<%= form_for(@location, :url => (@location.new_record? ? locations_url : location_path(@location.title_for_slug))) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>
  
  <div class="form-group">
    <%= f.fields_for :image do |t| %>
      <%= t.label :pic, "Background Image (for best results upload 1500x750 image)" %> <br>

      <% if @location.image.present? %>
        <%= image_tag @location.image.pic.url(:big), id: 'location_image', class: 'mb15' %><br/>
      <% else %>
        <img id="location_image" class="mb5" src="#" alt="">
      <% end %>
      <% if current_page?('/locations/new') %>
        <%= t.file_field :pic, class: "form-control", style: "padding: 4px;", required: true %>  
        <%#= t.file_field :pic, class: "form-control", style: "padding: 4px;" %>  
      <% else %>
        <%= t.file_field :pic, class: "form-control", style: "padding: 4px;" %>
      <% end %>

    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.cktext_area :description, class: "form-control ckeditor" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :fax %>
    <%= f.text_field :fax, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :general_contact_email %>
    <%= f.text_field :general_contact_email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :specific_location %>
    <%= f.text_field :specific_location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :title_for_maps %>
    <%= f.text_field :title_for_maps, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :iframe, "iframe link (set height and width to 100%)" %>
    <%= f.text_area :iframe, rows: 3, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "form-control btn btn-primary" %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/locations/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/locations/show.html.erb
<% provide(:title, "GCG Events | #{@location.name} Event Catering") %>
<% content_for :head do%>
  <meta name="description" content='<%= "GCG Events #{@location.name} offers catering and planning for sports events, weddings, social events, government events, sports events, and corporate events." %>'>
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<!-- Hero  -->
<section class="hero-location" style="background-image: url(<%= @location.image.present? ? @location.image.pic.url(:big) : '//s3-us-west-2.amazonaws.com/gcg-catering/hero/hero-locations.jpg' ; %>);"></section>

<section class="about">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 text-left center-mobile">
        <h5 class="mb0 color-primary"><%= @location.name %> <%= link_to "(Edit Location)", edit_location_path(@location.title_for_slug) if current_user.try(:admin?) %> </h4>
        <p class="mt15"><%= @location.description.html_safe %></p>
      </div>
      <div class="col-sm-4 text-right center-mobile">
        <h5 class="mb0 color-primary">Contact Details</h5>
        <p class="mt15"><%= @location.specific_location %> <br/><%= @location.name %><br/>Phones(s): <%= @location.phone %><br/>Fax: <%= @location.fax %></p>
        <br>
        <a class="btn btn-default btnBlog" href="#contactourlocation">Contact Us</a>
      </div>
    </div>
    <div class="row mt60">
      <h5 class="mt30 mb60 text-center color-secondary">The Team <%= link_to "(Add new member)", new_profile_path(location_id: @location.id)  if current_user.try(:admin?)%></h5>
      <% @profiles.each do |profile| %>
      <div class="col-sm-4 text-center mb30 mobile50">
        <%= image_tag(profile.image.pic.url(:square), class: "img-circle img-responsive imgTeam center-block") if profile.image.present? %>
        <h6><%= profile.full_name %></h6>
        <p style="color: #888; line-height: 28px; font-weight: normal; font-size: 14px;">
          <%= profile.title %> 
        </p>
        <% if profile.telephone.present? %>
          <p style="color: #888; line-height: 28px; font-weight: normal; font-size: 14px;""><%= "Tel. #{profile.telephone}" %></p> 
        <% else %>
          <p style="color: #888; line-height: 28px; font-weight: normal; font-size: 14px; visibility: hidden;"><%= "Tel. #{profile.telephone}"%></p>
        <% end %>
        <% if current_user.try(:admin?) %>
          <div>Location: <%= profile.location.name %></div> <br>
          <div>Position: <%= profile.position %></div> <br>
          <div><%= link_to 'Edit', edit_profile_path(profile, location_id: @location.id), class:"btn btn-default btnBlog" if current_user.try(:admin?) %></div> <br>
          <div><%= link_to 'Destroy', profile_path(profile), class:"btn btn-default btnBlog", method: :delete, data: { confirm: 'Are you sure?' } if current_user.try(:admin?)%></div>
        <% end %>
      </div>
      <% end if @profiles.present?%>
      
    </div>
  </div>
</section>


<!-- Location  -->
<section class="bg-light-orange">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h5 class="mb60 text-center color-white">Our Location</h5>
        <div class="map map-container">
          <%= @location.iframe.html_safe if @location.iframe.present? %>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Form  -->
<section id="contactourlocation">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h5 class="mb60 text-center color-secondary">Send us a Message</h5>
        <div class="message">
          <%= form_for Contact.new, :html => { :id => "new_contact", :honeypot => true }, :url => {:controller => "contacts", :action => "create"} do |f| %>
            <%= hidden_field_tag :thislocation,  @location.id %>
            <div class="col-sm-4">
              <div class="form-group">
                <%= f.label :name, class: "sr-only" %>
                <%= f.text_field :name, class: "form-control", placeholder: "Full Name", required: true %>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group">
                <%= f.label :email, class: "sr-only" %>
                <%= f.email_field :email, class: "form-control", placeholder: "Email", required: true %>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group">
                <%= f.label :phone_number, class: "sr-only" %>
                <%= f.text_field :phone_number, class: "form-control", placeholder: "Phone", required: true %>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="form-group">
                <%= f.label :message, class: "sr-only" %>
                <%= f.text_area :message, class: "form-control", rows: 3, placeholder: "Message", required: true %>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group">
                <%= f.submit "Submit", class: "btn btn-default btn-xl btn-custom-primary" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>